on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: heybit/node:12.18
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change docker-compose network
        uses: ./ # Uses an action in the root directory
        id: change_network
        with:
          network-name: default
          compose-file: tests/docker-compose.yml
      - name: Assert
        if: ${{ steps.change_network.outputs['network-name'] != job.container.network }}
        run: exit 1

